[project]
name = "venv-finder"
version = "0.1.0"
description = "A simple Qt6 GUI for finding venv"
requires-python = ">=3.10"
dependencies = [
    "PySide6",
    "qasync",
    "pytest",
    "pytest-asyncio"
]
